# This PSM1 is for development purposes only. A complete module PSM1 can be
# generated by running build.psm1. This file should never be included in a
# released version of the module.

$LoadFolders = @(
    "$PSScriptRoot/module-init/"
    "$PSScriptRoot/private"
    "$PSScriptRoot/public"
)

$LoadFolders |
    Get-ChildIitem -Recurse -File -Include '*.ps1' |
    ForEach-Object {
        . $_.FullName
    }
